name: sham_coffee_worker
description: "تطبيق قهوة الشام للعمال - منيو الطلبات"
publish_to: 'none'

version: 1.2.0+3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  http: ^1.2.2
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  google_fonts: ^7.0.2
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
