name: sham_coffee_staff
description: Sham Coffee Staff App - Windows Desktop
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase - Using stable versions compatible with Windows
  firebase_core: ^3.15.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.1
  # Note: firebase_database doesn't support Windows Desktop, using REST API instead
  
  # HTTP for Firebase Realtime Database REST API (Windows Desktop compatible)
  http: ^1.2.0
  
  # State Management
  provider: ^6.1.1
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  
  # Icons
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

