name: mirmaia_worker
description: تطبيق العمال لنظام Mirmaia - يعمل حسب الصلاحيات
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  
  # State Management
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  
  # Utils
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
